name: ci
on: [push, pull_request]

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-sqlite3
            mingw-w64-x86_64-pdcurses
      - name: Configure
        shell: msys2 {0}
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: msys2 {0}
        run: cmake --build build --config Release
      - name: Smoke
        shell: msys2 {0}
        run: ./build/chub --version
